### ISSUE TITLE
Schliessen Button fehlerhaft nach Installation

### ISSUE THREAD

**Issue by designpilot** [OMOSde/contao-om-backend#19]
Hallo Rene
Das Modul als solches echt TOP und ein echter HELFER im BE, nur habe ich festgestellt, dass wenn ich nach der Installation im BE z.B. auf Themes -> Neues Theme dort dann bei Konfiguration -> Ordner auf Auswahl ändern klicke sehe ich unten rechts den Button Schliessen nicht mit dem Text Schliessen sondern mit folgenden Zeichen Schlie&szlig;en kannst Du mir sagen wie ich das beheben kann ??? Weil wenn ich das Modul wieder deinstalliere mit dem Contao Manager und danach nochmal schaue steht wieder ganz normal Schliessen dort.

**Comment by OMOSde** [comment]
Fixed in 57d87c772b0701cc656d7286da704d0b3556953c
