### ISSUE TITLE
Sitestructur : Call to a member function hasAccess() on null

### ISSUE THREAD

**Issue by kgansberger** [OMOSde/contao-om-backend#22]
get an internal error by clicking sitestruktur ( do=page )

````
Was ist das Problem?
Call to a member function hasAccess() on null
````

EDIT: just when "Layout-Button in Seitenstruktur ergänzen" is activated. (as Adminstator)

**Comment by OMOSde** [comment]
Which Contao version is used?

**Comment by kgansberger** [comment]
Contao 4.4.8

**Comment by OMOSde** [comment]
Can´t repoduce this issue. Hope this will fix it. 1b5cc6869438a32640475ae1238c46735f650e6f
