### ISSUE TITLE
illegal string while editing a module

### ISSUE THREAD

**Issue by rmfberlin** [OMOSde/contao-om-backend#23]
Warning: Illegal string offset 'install_tool' in /www/htdocs/w0106261/beautyshop2018tao/vendor/omosde/contao-om-backend/src/Resources/contao/classes/Toolbar.php on line 92

Warning: Illegal string offset 'new_template' in /www/htdocs/w0106261/beautyshop2018tao/vendor/omosde/contao-om-backend/src/Resources/contao/classes/Toolbar.php on line 98

Warning: Illegal string offset 'sync_files' in /www/htdocs/w0106261/beautyshop2018tao/vendor/omosde/contao-om-backend/src/Resources/contao/classes/Toolbar.php on line 104

Warning: Illegal string offset 'stylesheets' in /www/htdocs/w0106261/beautyshop2018tao/vendor/omosde/contao-om-backend/src/Resources/contao/classes/Toolbar.php on line 131

Warning: Illegal string offset 'modules' in /www/htdocs/w0106261/beautyshop2018tao/vendor/omosde/contao-om-backend/src/Resources/contao/classes/Toolbar.php on line 138

Warning: Illegal string offset 'layouts' in /www/htdocs/w0106261/beautyshop2018tao/vendor/omosde/contao-om-backend/src/Resources/contao/classes/Toolbar.php on line 145

Warning: Illegal string offset 'image_size' in /www/htdocs/w0106261/beautyshop2018tao/vendor/omosde/contao-om-backend/src/Resources/contao/classes/Toolbar.php on line 152

Warning: Illegal string offset 'stylesheets' in /www/htdocs/w0106261/beautyshop2018tao/vendor/omosde/contao-om-backend/src/Resources/contao/classes/Toolbar.php on line 131

Warning: Illegal string offset 'modules' in /www/htdocs/w0106261/beautyshop2018tao/vendor/omosde/contao-om-backend/src/Resources/contao/classes/Toolbar.php on line 138

Warning: Illegal string offset 'layouts' in /www/htdocs/w0106261/beautyshop2018tao/vendor/omosde/contao-om-backend/src/Resources/contao/classes/Toolbar.php on line 145

Warning: Illegal string offset 'image_size' in /www/htdocs/w0106261/beautyshop2018tao/vendor/omosde/contao-om-backend/src/Resources/contao/classes/Toolbar.php on line 152

**Comment by OMOSde** [comment]
Can´t reproduce this.

1. Exists the file vendor/omosde/contao-om-backend/src/Resources/contao/languages/de/default.xlf? (compare with github please)
2. Which backend language you use?

**Comment by Tastaturberuf** [comment]
I have the same, this is very strange to figure out. i can reproduce it with the Tao Theme from RockSolid:

- Use the app_dev.php entry point
- edit an RSCE element (RockSolid Custom Element)

The strange thing is, that the ```$GLOBALS['TL_LANG']['MSC']['om_backend'][*]``` offsets exists, but as arrays. 

I think the MSC-key is the wrong place for these translations, there must be in the default.php under
```$GLOBALS['TL_LANG']['om_backend'][*]```

But this is is not this problem.

**Comment by rmfberlin** [comment]
Yes, I've installed TAO-Template from Rocksolid also. But under pressure, because I'm working on a relaunch, I uninstalled OM-backend. I'm still waiting for an update.

**Comment by OMOSde** [comment]
Sry, but i have no Tao template for testing at the moment.

**Comment by OMOSde** [comment]
Should be solved with 349687c4e49eb5a2cb2de35e2a9f98168c719366.

I have organized a project with a Tao-Theme and can reproduce the problem. I can´t explain why it happen, but the changes seems to help.
