### ISSUE TITLE
HTML-Entitäten werden in den Übersetzungen wieder dekodiert

### ISSUE THREAD

**Issue by Tastaturberuf** [OMOSde/contao-om-backend#25]
https://github.com/contao/core-bundle/issues/1339

**Comment by Tastaturberuf** [comment]
Ich denke das Problem liegt hier: https://github.com/OMOSde/contao-om-backend/blob/master/src/Resources/contao/modules/ModuleBackendTabs.php#L179

**Comment by Tastaturberuf** [comment]
Mit ```return $doc->saveHTML();``` läuft das super. Ich bin mir aber nicht sicher wieso du das eingebaut hast.

**Comment by Tastaturberuf** [comment]
https://github.com/OMOSde/contao-om-backend/commit/57d87c772b0701cc656d7286da704d0b3556953c

**Comment by Tastaturberuf** [comment]
Ich vermute das ```htmlentities_decode()``` sollte ein ```htmlentities()``` werden?

**Comment by OMOSde** [comment]
Ich habe die Funktion in 91cadcd7f96215a5b1881fbee4d5b86a8072e1d5 entfernt. Wir müssen schauen, ob das wieder anderswo zu Problemen führt. Ich bin mir nicht mehr sicher, warum ich es implementiert habe.
