### ISSUE TITLE
 Problem with script tag in allowed HTML tags / settings

### ISSUE THREAD

**Issue by stefansl** [OMOSde/contao-om-backend#26]
I'm adding <script> to allowed HTML tags right at the beginning of the string
![bildschirmfoto 2018-02-28 um 22 55 26](https://user-images.githubusercontent.com/1564251/36816706-e7c4f6fe-1cde-11e8-84ad-d762153e4357.png)

In the system log appears a table (Contao 4.4.14 / 4.5.4)
![bildschirmfoto 2018-02-28 um 22 58 54](https://user-images.githubusercontent.com/1564251/36816716-f1d25e5c-1cde-11e8-98e7-062334e352bc.png)

Only with activated om_backend. 
Btw. great extension! 👍

**Comment by OMOSde** [comment]
Fixed in 91cadcd7f96215a5b1881fbee4d5b86a8072e1d5
