### ISSUE TITLE
Destroys backend in Isotope : product

### ISSUE THREAD

**Issue by futura-web** [OMOSde/contao-om-backend#27]
<img width="1038" alt="bildschirmfoto 2018-05-24 um 20 39 21" src="https://user-images.githubusercontent.com/6049752/40505667-46db4ac8-5f95-11e8-8a95-0e62cbe4c779.png">

**Comment by futura-web** [comment]
![bildschirmfoto am 2018-05-24 um 20 37 22-fullpage](https://user-images.githubusercontent.com/6049752/40505690-56f69318-5f95-11e8-97dc-dc3c7e781f4d.png)

**Comment by futura-web** [comment]
Somehow _om-backend_ kicks some elements out of the form @ _Isotope-eCommerce_.

**Comment by OMOSde** [comment]
The dom manipulation has a problem with the markup from the mediamanager from isotope. I don´t have solved the problem yet.

But you can comment out this line https://github.com/OMOSde/contao-om-backend/blob/master/src/Resources/contao/config/config.php#L114, if you dont use the backend tabs feature.

**Comment by OMOSde** [comment]
Fixed in 5ad48b6cb03103798424d664793ce7f62ac53203.

Switch from hook 'outputBackendTemplate' to 'getUserNavigation' for feature 'Backend-Tabs'.
