### ISSUE TITLE
Extras aktivieren/deaktivieren

### ISSUE THREAD

**Issue by ngdot** [OMOSde/contao-om-backend#32]
Wäre super wenn die einzelnen Bestandteile der Erweiterung aktivier-/deaktivierbar wären.
Im Prinzip wie "Backend-Links". Bei "Element-Klassen" wäre es aber super wenn auch das entsprechende DCA Feld mit deaktiviert wird.

PS: Super tolle Erweiterung, danke dafür!

**Comment by OMOSde** [comment]
Kannst du bitte kurz erklären, welche Bestandteile du aktivierbar/deaktivierbar machen würdest. (Das meiste ist es ja schon)

Kannst du bitte außerdem erklären, welches DCA-Feld bei Verwendung von "Element-Klassen" abgeschaltet werden soll?

**Comment by ngdot** [comment]
Hi, es wäre super wenn z.B die Icons (Schnelleinstiege) auf der rechten Seite einzeln aktivierbar/deaktivierbar (vielleicht auch sortierbar?) wären. Ebenfalls denke ich, dass man auch die "Element-Klassen" aktivierbar/deaktivierbar machen sollte, und in diesem Zuge dann die Klassenzuweisung in einem Inhaltslement oder im Artikel ausblenden sollte. Vielleicht wäre es auch interessant die Schnelleinstiege selbständig erweitern zu können, sprich dort einen eigenen Backend-Link mit Icon anzulegen.

**Comment by OMOSde** [comment]
Bei Verwendung der Element-Klassen das Feld ID/CSS auszublenden halte ich nicht für sinnvoll. Gegebenenfalls möchte man ja trotzdem derartige ergänzen. Für Redakteure kann bei Bedarf das Feld per Rechte-Management entfernt werden.

Über die andere Dinge muss ich mir Gedanken machen.

**Comment by ngdot** [comment]
Nein, nicht die Felder ID/CSS ausblenden, dass wäre totaler quatsch! Ich meine das multiple checkbox Menü darunter. 
![screenshot-192 168 50 11-2018 07 19-14-22-59](https://user-images.githubusercontent.com/8327905/42942231-8154be00-8b5f-11e8-9d0e-733599563adc.jpg)

**Comment by OMOSde** [comment]
Ah ok, verstehe. Das ergibt tatsächlich mehr Sinn.

**Comment by OMOSde** [comment]
Ich habe mich gegen ein Verstecken des Feldes 'Vordefinierte Stile' (auch in Version 2.0) entschieden. Auch wenn keine Stile definiert sind, ist dies eine Information. Wer das Feld gar nicht braucht, kann es über das Rechte-Management ausblenden.

Bzgl. der konfigurierbaren Buttons in der Toolbar wird es in der Version 2.0 die Möglichkeit geben, dies über einen Hook zu realisieren. Direkt konfigurierbar im Backend wird es nicht. Ich möchte das Modul grundsätzlich einfach halten und nicht Konfigurationen überfluten.

Daher schließe ich das Ticket hier.
