### ISSUE TITLE
Switch to new multicolumnwizard bundle

### ISSUE THREAD

**Issue by OMOSde** [OMOSde/contao-om-backend#34]
https://github.com/menatwork/contao-multicolumnwizard-bundle

**Comment by Ainschy** [comment]
Wann ist damit zu rechnen? Durch ein die bestehende Abhängigkeit lassen sich andere Erweiterungen nicht einsetzen.

**Comment by OMOSde** [comment]
Welche Erweiterungen würde das betreffen? Falls möglich hätte ich gerne die zugehörige composer.json zum testen. Gerne an rene.fehrmann@omos.de.

**Comment by Ainschy** [comment]
https://github.com/contao-community-alliance/merger2 wollte ich installieren, ist eine Contao 4.9.3 Installation.

**Comment by OMOSde** [comment]
Ich werde mir das Problem am Wochenende mal anschauen.

**Comment by Ainschy** [comment]
Ich teste gerade Lokal die Umstellung und melde mich dann

**Comment by OMOSde** [comment]
composer remove omosde/contao-om-backend
composer require contao-community-alliance/merger2 omosde/contao-om-backend

Das sollte gehen, dann wird das Bundle installiert. (getestet)

**Comment by OMOSde** [comment]
Changed in 531f6339fd4b4c55b3adf4624e7f4d5fb355e3b0
