### ISSUE TITLE
Kein Backendzugriff nach Update von Symfony Bundles

### ISSUE THREAD

**Issue by planepix** [OMOSde/contao-om-backend#37]
Hallo René,

nach einem Update von Symfony-Bundles einer 4.8.1 Installation kommt es zu einem Fehler beim Versuch, sich im Backend anzumelden.

Im Moment durch Deinstallation gelöst:
Das Ticket inkl. Fehlerbeschreibung und Stack Trace:
https://github.com/contao/contao/issues/683

Beste Grüße
Thomas

**Comment by OMOSde** [comment]
Hi Thomas,

ich schaue es mir an. Wohl aber erst am Wochenende. 4.8 habe ich tatsächlich noch nicht getestet. Melde mich dann hier. Danke fürs melden.

Viele Grüße
René

**Comment by OMOSde** [comment]
Hallo Thomas,

tritt das Problem nur auf, wenn du versuchst, dich als Nicht-Admin anzumelden? Und nutzt die Funktion 'Reihenfolge der BackendModule' in den Systemeinstellungen?

Viele Grüße
René

**Comment by planepix** [comment]
Hallo René,
in der Installation, in der der Fehler auftritt, gibt es nur einen Admin.
Reihenfolge meine ich genutzt zu haben, ja.

Soll ich eine erneute Installation versuchen?
Beste Grüße
Thomas

**Comment by planepix** [comment]
Eben noch mal neu installiert, Version 1.5.1.
Als Admin eingeloggt, dann einmal die Reihenfolge geändert, gesichert.
Immer noch als Admin eingeloggt.

In den Profileinstellungen mal alle Optionen angeklickt.
Werde es die Tage beobachten und Feedback geben.
Danke dir.
Grüße
Thomas

**Comment by OMOSde** [comment]
Fixed in ee9a101a241c81454a4100f3e8b130676fbae7fc

**Comment by OMOSde** [comment]
Das Problem entsteht im Zusammenspiel zwischen der Funktion für die Reihenfolge der Backendmodule und des Bundles 'cliffparnitzky/DirectContentElements' wie es die Hauptnavigation verändert - ich analysiere weiter

**Comment by OMOSde** [comment]
Das Problem tritt auch in einer neuen 4.8.1 auf, in der nur das Bundle 'cliffparnitzky/direct-content-elements' installiert ist. (komplett ohne omosde/contao-om-backend).

Ticket: https://github.com/cliffparnitzky/DirectContentElements/issues/13
