### ISSUE TITLE
Redirecting /contao/install to /contao/login after installation 

### ISSUE THREAD

**Issue by hella-schu** [OMOSde/contao-om-backend#38]
Hi Rene,
thanks for this great extension, I love it!
Since some days I have a problem after installing contao-om-backend (contao 4.4.44): I can't update the database because I'm getting always redirected from /contao/install to /contao/login.
After de-installation everything is fine again.
Best wishes, Hella

**Comment by OMOSde** [comment]
I could not reproduce the described behavior in a newly installed Contao 4.4.44.

But I added a query to the route "/contao/install" in config.php. This does not integrate the features of the module in the install tool.

I hope this fixes your problem. Fix in c741b6d68f0fd0a474be8983b8f603f17a80ff39

**Comment by hella-schu** [comment]
Thanks a lot for your quick reaction! I've updated the extension and my problem is solved.
