### ISSUE TITLE
Installtool löscht Tabelle tl_cfg_tag_node

### ISSUE THREAD

**Issue by heimseiten** [OMOSde/contao-om-backend#39]
Beim Hinzufügen der Erweiterung löscht das Installtool die Tabelle tl_cfg_tag_node obwohl diese von der Erweiterung terminal42/contao-node verwendet wird.

Danke für die tollte Erweiterung!

**Comment by OMOSde** [comment]
Das lässt mich jetzt etwas ungläubig zurück, aber ich kann das am Wochenende gerne mal testen.

**Comment by heimseiten** [comment]
<img width="2551" alt="Bildschirmfoto 2019-11-08 um 13 56 10" src="https://user-images.githubusercontent.com/6552484/68478174-984b1f80-022f-11ea-98b4-412f1989c805.png">
<img width="1001" alt="Bildschirmfoto 2019-11-08 um 13 56 20" src="https://user-images.githubusercontent.com/6552484/68478175-984b1f80-022f-11ea-8f62-5cd7a67ca614.png">

Kann es mir nicht anders erklären, es sind nur diese beiden Erweiterungen installiert.

**Comment by OMOSde** [comment]
Fixed in 3b65dd505c88298df1fc0b15eeea1b44864ff874
