### ISSUE TITLE
CSS-Klassen der Elementklassen fehlen in der Frontendausgabe

### ISSUE THREAD

**Issue by OMOSde** [OMOSde/contao-om-backend#41]
Siehe: https://community.contao.org/de/showthread.php?76653-om-backend-Elementklassen&p=515836#post515836

**Comment by OMOSde** [comment]
Fixed in 7749e5f57403222a27a415b0b519c1043247f53f

**Comment by mlwebworker** [comment]
Ich komme noch mal auf das Problem zurück. Bei meinem Test neulich hatte ich normale Core Elemente genutzt (Text und Artikel). Heute habe ich in der Installation ein RS-Custom-Element im Einsatz. Dort kommen die Klassen im Frontend noch immer nicht an. Funktioniert das für Custom-Elements gar nicht oder gibt es noch einen Fehler?

**Comment by OMOSde** [comment]
Das ist tatsächlich nicht berücksichtigt. Ich finde den Gedanken aber interessant und werde es mir anschauen.

**Comment by mlwebworker** [comment]
Danke

**Comment by OMOSde** [comment]
Das war jetzt leichter als gedacht. Neue Version 1.6.6 verfügbar.

Added in 74b992a388b837290918415936bf46d767e34a29

**Comment by mlwebworker** [comment]
Danke habe es gerade getestet funktioniert soweit. Wobei es komischer Weise bei mir ein Custom-Element gibt, dass sich nicht speichern lässt als Inhaltselement bei den Elementklassen. Dem werde ich bei Gelegenheit mal auf den Grund gehen.

**Comment by OMOSde** [comment]
Falls möglich kannst du mir das RSCE gerne zur Verfügung stellen. Dann würde ich selbst mal schauen.
