### ISSUE TITLE
Backend-Links der Erweiterung geht mit Contao 4.9.2 nicht

### ISSUE THREAD

**Issue by Kahmoon** [OMOSde/contao-om-backend#55]
Servus,

habe gerade eben ein System von Contao 4.8.x auf 4.9.x aktualisiert. Das Modul ist zwar nach wie vor installiert und ich kann auch Einstellungen vornehmen, allerdings werden mir die Features im Backend nicht mehr angezeigt. Damit meine ich jetzt z.B. die Shortlinks

Ich vermute es liegt daran das C 4.9.x die linke Navigation anders aufbaut. Ist ja seit Contao 4.9 alphabetisch sortiert.

IDs mit Shift anzeigen funktioniert noch

Wenn ich weiter debuggen kann bitte sagen. Da helfe ich gerne :)

**Nachtrag:** Shortlinks in die Top Navigation hinzufügen geht nach wie vor. Das bestätigt noch mal meine Vermutung bezüglich der Änderung an der linken Navigation.

VG Frank

**Comment by OMOSde** [comment]
Duplicate of #50

**Comment by Kahmoon** [comment]
Oh sorry...den habe ich irgendwie übersehen.

Der ist von Februar :-(
