### ISSUE TITLE
Backend CSS a:link

### ISSUE THREAD

**Issue by Ainschy** [OMOSde/contao-om-backend#56]
Der Overwrite in der Backend CSS verhindert bei einer Installation die Darstellung der Hintergrundfarbe bei a:link aus einer anderen Erweiterung.

Aus welchem Grund wird hier !important verwendet?

**Comment by OMOSde** [comment]
Kann ich aus dem Kopf jetzt gar nicht beantworten. Der Quelltext gibt leider nicht viel her. Ich werde aber alle Issues in der kommenden Version 2.0 berücksichtigen.

**Comment by Ainschy** [comment]
Das Problem ist das andere Erweiterungen z.B. Stock Management - eine Erweiterung für isotope eCommerce mittels geänderter Background-Color den Status anzeigt des Lagerstandes anzeigen.

**Comment by OMOSde** [comment]
Ich habe zumindest den Grund der CSS-Anweisung gefunden. Die System-Informationen (PHP-Info) bringt eigenes CSS mit und überschreibt damit das Backend. Nicht sicher, wie ich das aktuell besser lösen kann.

**Comment by Ainschy** [comment]
Vllt. in einem iFrame rendern lassen?

**Comment by Ainschy** [comment]
schau mir hier 

[https://stackoverflow.com/questions/6035850/is-there-a-way-to-force-phpinfo-to-output-its-stuff-without-formatting-just-l](url)

[http://www.php.net/manual/en/function.phpinfo.php#87463](url)

**Comment by OMOSde** [comment]
Ich habe in der Version 2.0 nun eine Lösung ohne iFrame (die mag ich nicht so) und ich möchte die Original-Optik gerne beibehalten. Ich werde dann wohl morgen für die 1.6 eine ähnliche Lösung implementieren und bereitstellen.

**Comment by OMOSde** [comment]
Fixed in b50cf294426f3c21aab5f9bfac32d6b59b72232e
