### ISSUE TITLE
Sprache zu Startpunkten hinzufügen - vertical-align

### ISSUE THREAD

**Issue by operatorone** [OMOSde/contao-om-backend#57]
Um die Sprache, die an den Startpunkt angefügt wird, könnte die Formatierung wie folgt angepasst werden, um auf gleicher Höhe dargestellt werden.

```
<div class="tl_left" style="...">
    <img src="system/themes/flexible/icons/folMinus.svg" alt="" style="margin-right:2px" width="18" height="18"></a>
    <a href="contao/preview?page=1" title="" target="_blank"><img src="system/themes/flexible/icons/root.svg" alt="" data-icon="root.svg" data-icon-disabled="root_1.svg" width="18" height="18"></a> <a href="..." title="">
    <strong>SEITENNAME</strong></a><strong> (DE)</strong>
</div>
```

Vielleicht könnte der Code entsprechend angepasst werden. Styles können natürlich auch nicht "inline" in einer Datei gespeichert sein. Dies dient nur der Vermittlung des Vorgehens.

```
    ..." title="">
    <strong>SEITENNAME</strong></a><span class="font-weight: bold; vertical-align: middle;">(DE)</span>
</div>
```

**Comment by OMOSde** [comment]
Kannst du bitte mal einen Screenshot des Problems posten? Bei mir scheint das korrekt.

**Comment by operatorone** [comment]
Na klar. Hier der Screenshot. Browser Firefox 79 Macos
![sprache-startpunkt](https://user-images.githubusercontent.com/4036452/91129194-decc1680-e6a9-11ea-9a5e-840d69a9c1c0.jpg)

**Comment by OMOSde** [comment]
Fixed in e85396e566fb2df6b22a045e37392caed6d09b2a
