### ISSUE TITLE
Update wa72/htmlpagedom dependency (and code if necessary)

### ISSUE THREAD

**Issue by fritzmg** [OMOSde/contao-om-backend#63]
Currently this extension requires `wa72/htmlpagedom` in version `^1.3`. However there is one problem: versions `1.3.2` through `1.4.2` (the newest 1.x version) of this package are incompatible with Symfony 4.4 or higher. Thus only version `1.3.1` of this package can be installed in Contao 4.9 and up. This makes it more difficult to install this extension in Contao 4.11, because  `wa72/htmlpagedom` would need to be downgraded.

There is however a version `2.x`, which supports a better range of Symfony versions.

**Comment by OMOSde** [comment]
I have looked at the problem and found that the library is only used in one place in the code. I think the best thing will be to modify the code so that the dependency can be removed.

**Comment by OMOSde** [comment]
Changed in b8d7b244b89bf20d2308cf904ff46b0e14608f5c
