### ISSUE TITLE
Backend bei z.B. Bildauswahl - Inhalt der Lightbox wird nicht korrekt aufgebaut/dargestellt

### ISSUE THREAD

**Issue by berecont** [OMOSde/contao-om-backend#64]
Contao 4.9.13
contao-om-backend 1.6.12
Die Darstellung in der Lightbox wird nicht korrekt "aufgebaut" - es gibt kein CSS und der Button "Anwenden" funktioniert auch nicht.
Sofern ich das korrekt eingrenzen konnte, geht es um das `<iframe>` im `<div class="simple-modal-body">` welches nicht wie gewünscht, wie erwartet umgesetzt wird.

Nach Deinstallation funktioniert's wieder korrekt.

**Comment by OMOSde** [comment]
Das Problem entsteht mit der Änderung in der 1.6.12. Als Workaround sollte es helfen, die Funktion 'Prüfe Contao-Version' in den Systemeinstellungen abzuschalten.

**Comment by OMOSde** [comment]
Fixed in 4efd21328ec128829a47059e09fb147829fe2332
