### ISSUE TITLE
InsertTags im Markdown-Viewer ersetzen

### ISSUE THREAD

**Issue by do-while** [OMOSde/contao-om-backend#65]
Zum Beispiel beim Aufbau von seiteninternen Links wäre es hilfreich, wenn InsertTags aufgelöst werden würden.
```
Inhaltsverzeichnis:
* [Seitentexte und Bilder]({{env::url}}/{{env::request}}#artikel)
* [Dateiverwaltung]({{env::url}}/{{env::request}}#files)
```
Ich habe dazu das Template `mod_markdown_viewer.html5` angepasst:
Zeile 38:
`<?php if ($this->html): ?><?=$this->html; ?><?php endif; ?>`
neu:
`<?php if ($this->html): ?><?= \Contao\Controller::replaceInsertTags($this->html, false); ?><?php endif; ?>`

Dann sind die Links funktionstüchtig.

**Comment by OMOSde** [comment]
Hi,

ich kann dir deinen Wunsch gerne erfüllen (das funktioniert dann natürlich nur im Backend). Ich würde den Aufruf aber ins Modul übernehmen und nicht ins Template.

Ich habe aber noch eine Frage: Deine Beispiele oben lösen aber doch nicht zur Dateiverwaltung oder zu den Artikeln auf? Sind das einfach nur ungetestete Beispiele oder stehe ich auf dem Schlauch?

**Comment by do-while** [comment]
Nein, die Beispiele sind aus der Praxis:

```
Inhaltsverzeichnis:
* [Seitentexte und Bilder]({{env::url}}/{{env::request}}#artikel)
* [Dateiverwaltung]({{env::url}}/{{env::request}}#files)

```

weiter unten in der .md-Datei stehen dann die Anker in den Überschriften zu den Kapiteln:
```
# <a id="artikel"></a>Seitentexte und Bilder
           :
# <a id="files"></a>Dateiverwaltung
           :
```
Da geht es natürlich nicht zur Dateiverwaltung, sondern zu meinen Hilfetexten, die dem Redakteur die Besonderheiten erklären.

**Comment by OMOSde** [comment]
Ah, jetzt habe ich es verstanden.

Hinzugefügt in ac7fef8636a70799d77d84f83552857b8e474f61

**Comment by do-while** [comment]
Danke :-)

**Comment by OMOSde** [comment]
Neue Version ist bereits erstellt.
