### ISSUE TITLE
PHP 8: Non-static method Versions::replaceVersionTag() cannot be called statically

### ISSUE THREAD

**Issue by stefansl** [OMOSde/contao-om-backend#66]
Using PHP 8 om-backend throws an error:
`Non-static method OMOSde\ContaoOmBackendBundle\Versions::replaceVersionTag() cannot be called statically`

**Comment by OMOSde** [comment]
Should be solved in 082071403cba9c667c099d43de7f9b2a7c37b13f. 
Version 1.7.0 is released.
