### ISSUE TITLE
Seit Version 1.7.3 nur noch mit Contao 4.13 kompatibel?

### ISSUE THREAD

**Issue by keved93** [OMOSde/contao-om-backend#71]
Moin,
seit deiner Änderungen im Releases mit dem Tag 1.7.3 scheint dein Bundle nur noch mit Contao ^4.13 kompatibel zu sein. Alles darunter bricht aufgrund der Anpassung in /src/Resources/contao/classes/toolbar.php (Zeile 45 mit contao.backend.route_prefix) weg.

VG :)

**Comment by OMOSde** [comment]
Danke. Das war natürlich nicht gewollt.

Fixed in https://github.com/OMOSde/contao-om-backend/commit/0aad34b6c09bc3d11e00ba77556e393f086df5db
