### ISSUE TITLE
User returns NULL

### ISSUE THREAD

**Issue by raynor84** [OMOSde/contao-om-backend#72]
Hi,

using 
Contao 4.13.14
PHP 8.1.17

The code in the config:
`$objUser = System::getContainer()->get('security.helper')->getUser();`

doesn't return a User, even if logged as admin.

I changed it to:
```
        $objUser = BackendUser::getInstance();
        $objUser->authenticate();
```

and now i get the Links shown in the Backend. 

Could you have a look at it?

Kind regards

Stefan

**Comment by OMOSde** [comment]
Fixed in b37fd0858028e596f7bfb931ed9738c8f78afb0a
