### ISSUE TITLE
OM-Backend Links fehlen

### ISSUE THREAD

**Issue by Kahmoon** [OMOSde/contao-om-backend#73]
Seit den letzten beiden Updates fehlen Menüpunkte von OM Backend (Version 1.7.3 und 1.7.4).
<img width="195" alt="SCR-20230417-jshx" src="https://user-images.githubusercontent.com/6390770/232431503-acee9c48-5aef-4a82-80ab-e3c1f16586cb.png">

Bei 1.7.2 sah es noch so aus.
<img width="201" alt="SCR-20230417-jurz" src="https://user-images.githubusercontent.com/6390770/232432785-130df3ed-7cfd-4c0a-8fd5-3420af30aa64.png">

**Comment by OMOSde** [comment]
Fixed in b37fd0858028e596f7bfb931ed9738c8f78afb0a
